resolver: nightly-2022-04-06

# uncomment for static executables
# docker:
#   enable: true
#   image: utdemir/ghc-musl:v24-ghc922

packages:
- .

extra-deps:
- git: https://github.com/soupi/twain.git
  commit: 66200defb92a09560a9ae6ea618ee17278280bf4

allow-newer: true
