resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/16.yaml

# uncomment for static executables
# docker:
#   enable: true
#   image: utdemir/ghc-musl:v16-ghc884

packages:
- .
